### ISSUE TITLE
Add License

### ISSUE THREAD

**Issue by coding46** [SecSign/SecSign-ID-Typo3-Plugin#1]
Is there a way you might put a LICENSE.txt or LICENSE.md into the extension folder?

I'd like to finish and push a version compatible with TYPO3 7 LTS (and maybe 8) but without a license note for all of the files contained it is currently not possible legally.

Thanks in advance.

**Comment by secsignid** [comment]
Hi Göran,

thanks for the hint of the missing licence. We just added a LICENSE file to our typo3 repository.

**Comment by coding46** [comment]
Thank you!
